name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run app
        run: python main.py

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        run: echo "Deploy realizado com sucesso"
